name: Build and release Go binary

on:
  pull_request:
    types:
      - closed
    branches:
      - master
  workflow_dispatch:

jobs:
  create-release:
    name: Create new release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create release
        id: create-release
        uses: Koenigseder/semver-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-branch: master
          semver-prefix: v
          semver-start-version: 0.0.1

      - name: Output result (new release)
        if: ${{ steps.create-release.outputs.new-release-tag != '' }}
        env:
          NEW_RELEASE_TAG: ${{ steps.create-release.outputs.new-release-tag }}
        run: |
          printf "### :heavy_check_mark: Created new release for this PR\n\nNew release: \`$NEW_RELEASE_TAG\`" >> "$GITHUB_STEP_SUMMARY"

      - name: Output result (no new release)
        if: ${{ steps.create-release.outputs.new-release-tag == '' }}
        env:
          MAJOR_RELEASE_LABEL: ${{ steps.create-release.outputs.major-release-label }}
          MINOR_RELEASE_LABEL: ${{ steps.create-release.outputs.minor-release-label }}
          PATCH_RELEASE_LABEL: ${{ steps.create-release.outputs.patch-release-label }}
        run: |
          printf "### :x: No new release was created for this PR\n\nIn order to create a release set a valid label:\n\n- Major release: \`$MAJOR_RELEASE_LABEL\`\n- Minor release: \`$MINOR_RELEASE_LABEL\`\n- Patch release: \`$PATCH_RELEASE_LABEL\`" >> "$GITHUB_STEP_SUMMARY"

  go-build:
    runs-on: ubuntu-latest
    needs: create-release
    if: ${{ steps.create-release.outputs.new-release-tag != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Go build
        env:
          TAG: ${{ needs.create-release.outputs.new_release_tag }}
        shell: bash
        run: ./scripts/build.sh

      - name: Upload binary to release
        env:
          TAG: ${{ needs.create-release.outputs.new_release_tag }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: ./scripts/release.sh
